"""added receipts

Revision ID: 18e3df8ab0fb
Revises: 900246d43173
Create Date: 2023-05-07 05:22:38.249341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e3df8ab0fb'
down_revision = '900246d43173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ltcFormId', sa.Integer(), nullable=True),
    sa.Column('taFormId', sa.Integer(), nullable=True),
    sa.Column('formId', sa.Integer(), nullable=False),
    sa.CheckConstraint('"ltcFormId" IS NULL OR "taFormId" IS NULL', name='either_ltc_or_ta'),
    sa.ForeignKeyConstraint(['ltcFormId'], ['ltc_infos.id'], ),
    sa.ForeignKeyConstraint(['taFormId'], ['ta_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    # ### end Alembic commands ###
