"""added last forward date

Revision ID: 43012af68717
Revises: dcac92142a00
Create Date: 2023-05-09 03:11:48.716375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43012af68717'
down_revision = 'dcac92142a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltc_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastForwardDate', sa.DateTime(), nullable=True))

    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastForwardDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.drop_column('lastForwardDate')

    with op.batch_alter_table('ltc_infos', schema=None) as batch_op:
        batch_op.drop_column('lastForwardDate')

    # ### end Alembic commands ###
