"""removed unwanted receipts attrib

Revision ID: 595ebaf74b54
Revises: 2f65b615f595
Create Date: 2023-05-07 07:06:09.331937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ebaf74b54'
down_revision = '2f65b615f595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('formId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formId', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
