"""added expected journey details

Revision ID: 8ca12395c0df
Revises: 43012af68717
Create Date: 2023-05-12 21:39:25.223947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca12395c0df'
down_revision = '43012af68717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_journey_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ltcId', sa.Integer(), nullable=False),
    sa.Column('departureFrom', sa.String(), nullable=False),
    sa.Column('arrivalTo', sa.String(), nullable=False),
    sa.Column('modeOfTravel', sa.String(), nullable=False),
    sa.Column('noOfFares', sa.Integer(), nullable=False),
    sa.Column('singleFare', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ltcId'], ['ltc_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expected_journey_details')
    # ### end Alembic commands ###
