"""added fildate

Revision ID: 900246d43173
Revises: 
Create Date: 2023-05-06 17:50:05.577518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900246d43173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fillDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.drop_column('fillDate')

    # ### end Alembic commands ###
