import { user1 } from "./user";

const ltcInfoOld = [
  {
    id: 2,
    user: user1,
    fromDate: "2022-05-11",
    toDate: "2022-05-20",
    prefixFrom: null,
    prefixTo: null,
    suffixFrom: "2022-05-21",
    suffixTo: "2022-05-22",
    spouseEntitled: true,
    earnedLeaveAvailed: 0,
    natureOfTravel: "home",
    placeToVisit: "dehradun",
    totalEstimatedFare: 60000,
    advanceRequired: false,
    encashmentAvailed: false,
    encashmentNoOfDays: 0,
    stageRedirect: null,
    stageCurrent: 1,
    fillDate: "2022-05-08",
    dateLog: {
      0: null,
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
      9: null,
      10: null,
      11: null,
      12: null,
    },
    peopleInvolved: [
      {
        id: 1,
        name: "Tj",
        age: 21,
        relation: "gf",
        fromPlace: "punjab",
        toPlace: "dehradun",
        back: true,
        modeOfTravel: "plane",
      },
      {
        id: 2,
        name: "Avi",
        age: 21,
        relation: "gf",
        fromPlace: "punjab",
        toPlace: "dehradun",
        back: true,
        modeOfTravel: "plane",
      },
    ],
  },
];

export { ltcInfoOld };
